// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9SDl2CHPVKaL7HZJWva-WosI4xZ3HMgQ',
    appId: '1:664247167161:web:2d4c9ca409006834481368',
    messagingSenderId: '664247167161',
    projectId: 'studymate-36a1d',
    authDomain: 'studymate-36a1d.firebaseapp.com',
    storageBucket: 'studymate-36a1d.firebasestorage.app',
    measurementId: 'G-6HP0XVMGQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzrE9BGGcR-NsMvgaNGFH-529dfVVxeuw',
    appId: '1:664247167161:android:a9fdfbaa072aed19481368',
    messagingSenderId: '664247167161',
    projectId: 'studymate-36a1d',
    storageBucket: 'studymate-36a1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMb4fBIaUkAhd4kDS_u5knWvLWy8RSW6k',
    appId: '1:664247167161:ios:5a818126c8019228481368',
    messagingSenderId: '664247167161',
    projectId: 'studymate-36a1d',
    storageBucket: 'studymate-36a1d.firebasestorage.app',
    iosBundleId: 'com.example.capstone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMb4fBIaUkAhd4kDS_u5knWvLWy8RSW6k',
    appId: '1:664247167161:ios:5a818126c8019228481368',
    messagingSenderId: '664247167161',
    projectId: 'studymate-36a1d',
    storageBucket: 'studymate-36a1d.firebasestorage.app',
    iosBundleId: 'com.example.capstone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9SDl2CHPVKaL7HZJWva-WosI4xZ3HMgQ',
    appId: '1:664247167161:web:be5ff49eea907309481368',
    messagingSenderId: '664247167161',
    projectId: 'studymate-36a1d',
    authDomain: 'studymate-36a1d.firebaseapp.com',
    storageBucket: 'studymate-36a1d.firebasestorage.app',
    measurementId: 'G-N2Z997WQG9',
  );

}