// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgdANj3tm66bdPMawrNzprW-K1tuYQeT8',
    appId: '1:632869261923:web:d2103190e536a23ccb5e56',
    messagingSenderId: '632869261923',
    projectId: 'capstone-66919',
    authDomain: 'capstone-66919.firebaseapp.com',
    storageBucket: 'capstone-66919.firebasestorage.app',
    measurementId: 'G-SM0KHFYEQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXAgFWjA8NM1-APb7o1nH60ST7FXdaQlA',
    appId: '1:632869261923:android:0ac5c1ecae7198aacb5e56',
    messagingSenderId: '632869261923',
    projectId: 'capstone-66919',
    storageBucket: 'capstone-66919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT9cvk8cn_GwnHRfEbZm6ZMOS59-4oDuY',
    appId: '1:632869261923:ios:f33ab8f87653b5f3cb5e56',
    messagingSenderId: '632869261923',
    projectId: 'capstone-66919',
    storageBucket: 'capstone-66919.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT9cvk8cn_GwnHRfEbZm6ZMOS59-4oDuY',
    appId: '1:632869261923:ios:f33ab8f87653b5f3cb5e56',
    messagingSenderId: '632869261923',
    projectId: 'capstone-66919',
    storageBucket: 'capstone-66919.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgdANj3tm66bdPMawrNzprW-K1tuYQeT8',
    appId: '1:632869261923:web:829bf554077902e1cb5e56',
    messagingSenderId: '632869261923',
    projectId: 'capstone-66919',
    authDomain: 'capstone-66919.firebaseapp.com',
    storageBucket: 'capstone-66919.firebasestorage.app',
    measurementId: 'G-MHCGLVVP9H',
  );
}
